export default {
  guide: [
    'index', 'getting-started', 'api', 'theming',
    {type: 'category', label: 'Generated API', items: [
      {type: 'autogenerated', dirName: 'api/generated'},
    ]},
    {type: 'category', label: 'Components', collapsed: false, items: [
      'components/index', 'components/button', 'components/card', 'components/input',
      'components/badge', 'components/label', 'components/checkbox', 'components/switch',
      'components/separator', 'components/progress', 'components/skeleton',
    ]},
    'safety', 'testing', 'parity', 'roadmap', 'verification',
    {type: 'category', label: 'Maintainers', items: [
      'architecture', 'performance', 'spec', 'publishing', 'licensing',
      {type: 'category', label: 'Decisions', items: [
        {type: 'autogenerated', dirName: 'decisions'},
      ]},
      {type: 'category', label: 'Work items', items: [
        {type: 'autogenerated', dirName: 'issues'},
      ]},
    ]},
  ],
};
